const definition = {
  NO_CYCLES: 'NO_CYCLES',
  HAS_INPUT_NODES: 'HAS_INPUT_NODES',
  HAS_PORTS_CONNECTED: 'HAS_PORTS_CONNECTED',
  HAS_REQUIRED_PARAMETERS_FILLED: 'HAS_REQUIRED_PARAMETERS_FILLED'
};
export default definition;
